"""The explicit, read-only SQL execution boundary.

SQL generated by a model is never passed directly to a database.  This module
first parses and clamps it with :mod:`guardrails`, then executes the guarded
statement through a short-lived SQLAlchemy connection.  It intentionally does
not support arbitrary connection strings in the UI layer; a workspace owns the
database URI that is supplied here.
"""

from __future__ import annotations

from dataclasses import dataclass
from time import perf_counter
from typing import Any

from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine
from sqlalchemy.exc import SQLAlchemyError

from apps.core.guardrails import GuardedSQL, SQLGuardrailError, SQLGuardrails


class QueryExecutionError(RuntimeError):
    """Raised when a guarded, read-only query cannot be executed."""


@dataclass(frozen=True)
class QueryResult:
    """Serializable result returned from the only database execution path."""

    sql: str
    limit: int
    columns: list[str]
    rows: list[dict[str, Any]]
    row_count: int
    elapsed_ms: int


class ReadOnlyExecutor:
    """Execute exactly one AST-validated SELECT against one data source."""

    def __init__(
        self,
        database_uri: str,
        *,
        max_rows: int = 500,
        dialect: str | None = "sqlite",
        timeout_seconds: int = 30,
    ) -> None:
        if not isinstance(database_uri, str) or not database_uri.strip():
            raise ValueError("database_uri must be a non-empty string")
        if isinstance(timeout_seconds, bool) or timeout_seconds <= 0:
            raise ValueError("timeout_seconds must be a positive integer")
        self.database_uri = database_uri
        self.timeout_seconds = timeout_seconds
        self.guardrails = SQLGuardrails(max_limit=max_rows, dialect=dialect)
        connect_args: dict[str, Any] = {}
        if database_uri.startswith("sqlite"):
            connect_args["timeout"] = timeout_seconds
        elif database_uri.startswith("postgresql"):
            connect_args["connect_timeout"] = timeout_seconds
        elif database_uri.startswith("mysql"):
            connect_args.update(
                {"connect_timeout": timeout_seconds, "read_timeout": timeout_seconds, "write_timeout": timeout_seconds}
            )
        self.engine: Engine = create_engine(database_uri, connect_args=connect_args)

    def prepare(self, proposed_sql: str) -> GuardedSQL:
        """Parse, reject writes/multiple statements, and apply an outer LIMIT."""

        return self.guardrails.validate_and_clamp(proposed_sql)

    def execute(self, proposed_sql: str) -> QueryResult:
        """Validate and run a query after the caller's explicit approval."""

        guarded = self.prepare(proposed_sql)
        started = perf_counter()
        try:
            with self.engine.connect() as connection:
                # SQLite's query_only is a second, database-level safety belt.
                # SQLGlot remains the primary cross-dialect read-only boundary.
                if self.database_uri.startswith("sqlite"):
                    connection.exec_driver_sql("PRAGMA query_only = ON")
                    raw_connection = connection.connection.driver_connection
                    deadline = started + self.timeout_seconds
                    # SQLite calls this regularly while evaluating virtual-machine
                    # instructions; a non-zero return safely interrupts the query.
                    raw_connection.set_progress_handler(
                        lambda: int(perf_counter() >= deadline), 1_000
                    )
                elif self.database_uri.startswith("postgresql"):
                    # A short-lived transaction is explicitly marked read-only,
                    # even when the connected database role is misconfigured.
                    connection.exec_driver_sql("SET TRANSACTION READ ONLY")
                    connection.execute(
                        text("SET LOCAL statement_timeout = :timeout_ms"),
                        {"timeout_ms": self.timeout_seconds * 1_000},
                    )
                elif self.database_uri.startswith("mysql"):
                    # The connection is disposed after every query, so this
                    # session-level setting cannot leak to other workspaces.
                    connection.exec_driver_sql("SET SESSION TRANSACTION READ ONLY")
                result = connection.execute(text(guarded.sql))
                columns = list(result.keys())
                rows = [dict(row) for row in result.mappings().all()]
        except SQLAlchemyError as exc:
            raise QueryExecutionError("The read-only query could not be executed.") from exc
        finally:
            # No transaction is committed: this executor is deliberately read-only.
            self.engine.dispose()
        elapsed_ms = max(0, round((perf_counter() - started) * 1000))
        return QueryResult(
            sql=guarded.sql,
            limit=guarded.limit,
            columns=columns,
            rows=rows,
            row_count=len(rows),
            elapsed_ms=elapsed_ms,
        )


__all__ = ["QueryExecutionError", "QueryResult", "ReadOnlyExecutor", "SQLGuardrailError"]
